name: pizza-palooza
services:
  backend:
    container_name: ${DB_DATABASE_NAME}
    image: postgres:16.4-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ./postgres:/database

volumes:
  postgres:
