name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      # Check out the source
      - name: Checkout Source
        uses: actions/checkout@v4
      # Setup node.js and cache
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Lint App
      - name: Lint App
        run: npm run format
      # Build App
      - name: Build App
        run: npm run build
      - name: Test
        run: npm test
