name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      # Check out the source
      - name: Checkout Source
        uses: actions/checkout@v4
      # Setup node.js and cache
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: ./backend/package.json
      # Install dependenci
      - name: Install dependenci
        run: |
          cd backend
          npm install
      - name: Formating files
        run: |
          cd backend
          npm run format
      - name: Build
        run: |
          cd backend
          npm run build
      - name: Testing
        run: |
          cd backend
          npm test
